# environment.yml
name: PharDDIE
channels:
  - pyg
  - dglteam
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  # 核心深度学习框架 (CUDA 11.8)
  - pytorch=2.0.1
  - torchvision=0.15.2
  - torchaudio=2.0.2
  - pytorch-cuda=11.8
  # 图神经网络库
  - dgl=2.1.0
  - pyg=2.6.1                     # torch-geometric
  # 化学信息学 & 分子对接
  - rdkit=2025.03.5
  - openbabel
  - pdb2pqr
  # 数据分析与科学计算
  - numpy=1.24.3
  - pandas
  - scikit-learn
  - scipy
  - matplotlib-base
  # 其他常用包
  - tqdm
  - joblib
  - pyyaml
  - pip:
    - dgllife==0.2.8
    - diffusers==0.21.4
    - meeko
    - propka
    - vina==1.2.2
    - autodocktools-py3
    - tensorboard
    - tensorboardX
    - hyperopt
    - coqpit
    - easydict
    - soundfile
    - lmdb
    - torchdata
    - psutil
    - future
    - packaging
    - regex
    - werkzeug
    - cloudpickle
    - filelock
    - huggingface-hub
    - safetensors
    - grpcio
    - protobuf
    - pycairo
    - cffi
    - brotlicffi
    - aiohttp
    - yarl
    - multidict
    - frozendict
    - propka
    - prettytable
    - reportlab
    - wcwidth
    - zipp
    - importlib-metadata
    - importlib-resources
    - cycler
    - fonttools
    - kiwisolver
    - contourpy
    - pillow
    - requests
    - certifi
    - urllib3
    - charset-normalizer
    - idna
    - annotated-types
    - pydantic
    - pydantic-core
    - typing-inspection
    - sniffio
    - anyio
    - h11
    - httpcore
    - httpx